apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopherservice
  labels:
    app: gopherservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gopherservice
  template:
    metadata:
      labels:
        app: gopherservice
    spec:
      containers:
      - name: gopherservice
        image: gopherservice:latest # Assuming you've built this image locally
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: GRPC_PORT
          value: "8080"
        - name: HTTP_PORT
          value: "8081"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "otel-collector:4317"
        - name: DATABASE_DSN
          value: "sqlite://gopherservice.db"
        # Add JWT_SECRET_KEY here if it's not handled by a Secret
        # - name: JWT_SECRET_KEY
        #   value: "your-jwt-secret-key"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gopherservice
  labels:
    app: gopherservice
spec:
  selector:
    app: gopherservice
  ports:
  - name: grpc
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
